### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by airpodshottyyoulookinrealsussy** [PhoenixTheCoder/official-nmpb-js#1]
keeps saying npm start npm is not recognized as an internal external operable program or batch file on run
i tried install d. already and gave me npm is not recognized as an internal or external command, operable program or batch file 
 call npm install -D electron@latest 'npm' is not recognized as an internal external command, operable program or batch file.
PAUSE
Press any key to continue . . .

**Comment by PhoenixTheCoder** [comment]
You have to download node.js first before running any of that.
You can get it here: https://nodejs.org/en/
After you install node.js then try to run it.
If you have any other issues just open a issue.
Thanks.
